---
#
# Playbook to install the ELK stack + Beats (for server performance)
#
- hosts: localhost
  remote_user: root
  become: yes
  become_user: root
  vars_files:
    - secrets.yml
  roles:
  - { role: ec2-dyn-inventory }
- hosts: node
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: logstash }
  - { role: kibana }
  - { role: metricbeat }
  - { role: some-data }
  - { role: restart-services }
